custom npm argument for environment
zurb/foundation-ssg pull request #40
Opened 2016-06-07 17:45 UTC by manuelcorrea

2016-06-17 15:51 UTC, rafibomb commented
I think this is a great change! It is a breaking change so we can push it to the next point release 6.3.
Are you able to point this change to the v6.3 branch so we can merge it in?

2016-06-17 16:05 UTC, manuelcorrea commented
@rafibomb it is already pointing to the 6.3 branch. Thanks!

2016-06-20 06:45 UTC, phifa commented
What does this actually do? The former ...`build` is now `build --production`? What is `build` now?

2016-06-20 12:28 UTC, manuelcorrea commented
@phifa It will be default, which I guess in this case is non-environment = development?

In our internal project we ended with 
```
"scripts": {
    "start": "gulp",
    "build": "gulp build --production",
    "build-production": "gulp build --production",
    "build-dev": "gulp build --development"
  },
``
Production will be the default and if you want the raw files for debugging then do a build-dev?

I didn't want to push this change to favor more flexibility on the script environment through cli.

Thoughts?

2016-06-20 12:29 UTC, manuelcorrea commented
Alternative the default can be set on the gulp file instead of the package.json ...

2016-11-16 07:06 UTC, colin-marshall requested changes

2016-11-16 07:06 UTC, colin-marshall commented on readme.md
> +To create compressed, production-ready assets, run `npm run build -- --production`.
There are two pairs of hyphens here. I believe this is a typo.

2016-11-17 13:59 UTC, manuelcorrea commented on readme.md
> +To create compressed, production-ready assets, run `npm run build -- --production`.
Hey Colin, it is not a typo. This is the way to pass arguments to npm scripts 
https://docs.npmjs.com/cli/run-script

```
As of npm@2.0.0, you can use custom arguments when executing scripts. The special option -- is used by getopt to delimit the end of the options. npm will pass all the arguments after the -- directly to your script:

npm run test -- --grep="pattern"
The arguments will only be passed to the script specified after npm run and not to any pre or post script.
```

2016-11-21 21:38 UTC, colin-marshall commented on readme.md
> +To create compressed, production-ready assets, run `npm run build -- --production`.
@manuelcorrea good to know, thanks!

2022-07-11 20:22 UTC, closed without merging