FIX gulpfile for vendor ES5
zurb/foundation-ssg pull request #43
Opened 2016-10-29 23:51 UTC by york-xtrem

## All the info here
https://github.com/zurb/foundation-sites/issues/9302

2016-11-24 16:12 UTC, shafi49 commented
I highly recommend this merge request. I also faced similar problems while trying to use [ScrollMagic](http://scrollmagic.io/). 
However I somehow got it working by ignoring those files in .babelrc file like this 
`{
	"presets": ["es2015-without-strict"],
	"ignore": [
	"bower_components/justgage/raphael-2.1.4.min.js",
	"bower_components/scrollmagic/scrollmagic/uncompressed/ScrollMagic.js",
	"bower_components/scrollmagic/scrollmagic/minified/plugins/animation.gsap.min.js",
	"bower_components/scrollmagic/scrollmagic/minified/plugins/debug.addIndicators.min.js"
	],
  "compact": false
}`
In above code snippets I used "es2015-without-strict" to use [raphael.js](http://dmitrybaranovskiy.github.io/raphael/) library. 
Please consider this merge request so that people like me won't have to waste time trying to figure what went wrong.

2019-11-23 21:57 UTC, DanielRuf commented
Please resolve the conflicts.

2020-01-01 21:56 UTC, DanielRuf requested changes

2020-01-01 21:56 UTC, DanielRuf commented on config.yml
> +    # Libraries requried by Foundation
```suggestion
    # Libraries required by Foundation
```

2020-01-01 21:56 UTC, DanielRuf commented on config.yml
> +  # Paths to JavaScript libraries, which are compined into one file
```suggestion
  # Paths to JavaScript libraries, which are combined into one file
```

2022-07-11 20:22 UTC, closed without merging